github.com:
    users:
        Bailey-Moir:
            oauth_token: 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
    git_protocol: ssh
    user: Bailey-Moir
    oauth_token: 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
